/**
 * @file Web-to-ZIP Downloader plugin
 * @module plugins/tool/web2zip
 * @description Save websites as ZIP files using saveweb2zip API
 * @license Apache-2.0
 */

let handler = async (m, { sock, text, usedPrefix, command }) => {
    let url = text || (m.quoted?.text || "");
    url = url.trim();

    if (!url) {
        return m.reply(
            `📦 *SAVE WEB TO ZIP*\n\n` +
            `*Usage:*\n` +
            `${usedPrefix + command} (url)\n\n` +
            `*Example:*\n` +
            `${usedPrefix + command} https://google.com`
        );
    }

    if (!url.startsWith("http")) {
        url = "https://" + url;
    }

    try {
        await global.loading(m, sock);
        const statusMsg = await m.reply("⏳ *Processing...* Generating ZIP for the website.");

        const result = await saveweb2zip(url, {
            renameAssets: true,
            saveStructure: false,
            alternativeAlgorithm: false,
            mobileVersion: false
        });

        if (result.error?.text) {
            throw new Error(result.error.text);
        }

        const caption =
            `📦 *WEB TO ZIP*\n\n` +
            `│ • *URL:* ${result.url}\n` +
            `│ • *Files:* ${result.copiedFilesAmount || 0} files\n` +
            `│ • *Download:* ${result.downloadUrl}\n\n` +
            `⬇️ _Click the link above to download your ZIP file._\n` +
            `_Generated by Liora Bot_`;

        await sock.sendMessage(m.chat, {
            text: caption,
            edit: statusMsg.key,
            contextInfo: {
                externalAdReply: {
                    title: "Web to ZIP Downloader",
                    body: result.url,
                    thumbnailUrl: "https://files.catbox.moe/0zhmpq.jpg", // Default Liora thumb
                    mediaType: 1,
                    renderLargerThumbnail: true
                }
            }
        });

    } catch (err) {
        global.logger.error({ error: err.message, url }, "Web2Zip Error");
        m.reply(`❌ *Error:* ${err.message}`);
    } finally {
        await global.loading(m, sock, true);
    }
};

/**
 * Core function to interact with saveweb2zip api
 * @param {string} url 
 * @param {object} options 
 * @returns {promise<object>}
 */
async function saveweb2zip(url, options = {}) {
    try {
        if (!url) throw new Error("URL is required");

        const {
            renameAssets = false,
            saveStructure = false,
            alternativeAlgorithm = false,
            mobileVersion = false
        } = options;

        const headers = {
            "accept": "*/*",
            "content-type": "application/json",
            "origin": "https://saveweb2zip.com",
            "referer": "https://saveweb2zip.com/",
            "user-agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/137.0.0.0 Mobile Safari/537.36"
        };

        const res = await fetch("https://copier.saveweb2zip.com/api/copySite", {
            method: "POST",
            headers,
            body: JSON.stringify({
                url,
                renameAssets,
                saveStructure,
                alternativeAlgorithm,
                mobileVersion
            })
        });

        const data = await res.json();

        while (true) {
            const statusRes = await fetch(`https://copier.saveweb2zip.com/api/getStatus/${data.md5}`, { headers });
            const process = await statusRes.json();

            if (!process.isFinished) {
                await new Promise(resolve => setTimeout(resolve, 2000));
                continue;
            } else {
                return {
                    url,
                    error: {
                        text: process.errorText,
                        code: process.errorCode,
                    },
                    copiedFilesAmount: process.copiedFilesAmount,
                    downloadUrl: `https://copier.saveweb2zip.com/api/downloadArchive/${process.md5}`
                };
            }
        }
    } catch (error) {
        throw new Error(error.message);
    }
}

handler.help = ["web2zip", "saveweb", "downloadweb"];
handler.tags = ["tools"];
handler.command = /^(web2zip|saveweb|downloadweb)$/i;

export default handler;
