/**
 * @file OCR (Optical Character Recognition) plugin
 * @module plugins/tool/ocr
 * @description Extract text from images using staging-ai-image-ocr API
 * @license Apache-2.0
 * @author ayakashigh11
 */

/**
 * Process image OCR using external API
 * @param {Buffer} buffer - Image buffer
 * @returns {Promise<string>} - Extracted text
 */
async function processOCR(buffer) {
    const url = "https://staging-ai-image-ocr-266i.frontend.encr.app/api/ocr/process";
    const imageBase64 = buffer.toString("base64");

    const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
            imageBase64,
            mimeType: "image/png" // API seems to accept png as default, works for most images
        })
    });

    if (!res.ok) {
        const errText = await res.text();
        throw new Error(errText || `API error ${res.status}`);
    }

    const json = await res.json();
    return json.extractedText;
}

let handler = async (m, { sock, usedPrefix, command }) => {
    // Detect image in current message or quoted message
    const q = m.quoted ? m.quoted : m;
    const mime = (q.msg || q).mimetype || q.mediaType || "";

    if (!/image/.test(mime)) {
        return m.reply(`🎬 *OCR READER*\n\nUsage: Reply to an image or send an image with caption *${usedPrefix + command}* to extract text.`);
    }

    try {
        await global.loading(m, sock);

        const buffer = await q.download?.();
        if (!buffer) return m.reply("❌ Failed to download the image. Please try again.");

        await m.reply("⏳ *Processing OCR...* This may take a moment.");

        const text = await processOCR(buffer);

        if (!text || text.trim().length === 0) {
            return m.reply("❌ No text could be detected in this image.");
        }

        const caption = `📝 *OCR RESULTS*\n\n${text}\n\n_Generated by Liora Bot_`;

        await m.reply(caption);

    } catch (e) {
        global.logger.error({ error: e.message, stack: e.stack }, "OCR Plugin Error");
        m.reply(`❌ Error: ${e.message || "Failed to extract text from image."}`);
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["ocr", "readimg"];
handler.tags = ["tools"];
handler.command = /^(ocr|readimg)$/i;

export default handler;
