/**
 * @file IQC Maker plugin
 * @module plugins/maker/iqc
 * @description Create a quote image (IQC) using NexRay API
 * @license Apache-2.0
 * @author ayakashigh11
 */

let handler = async (m, { sock, text, usedPrefix, command }) => {
    if (!text && !m.quoted?.text) {
        return m.reply(`🎬 *IQC MAKER*\n\nUsage: *${usedPrefix + command} [text] | [provider] | [battery] | [time]*\nExample: *${usedPrefix + command} Hello World | STARLINK | 100 | 12:00*`);
    }

    try {
        await global.loading(m, sock);

        // Parsing arguments separated by "|"
        let [qText, qProvider, qBattery, qTime] = text.split("|").map(v => v.trim());

        // Text requirement
        if (!qText && m.quoted?.text) qText = m.quoted.text;
        if (!qText) return m.reply("❌ Please provide text for the quote.");

        // Defaults
        const provider = qProvider || "TELKOMSEL";
        const battery = qBattery || "32";

        // Default time to WIB (Current Time +07:00)
        let time = qTime;
        if (!time) {
            const now = new Date();
            // Since the system time is already in +07:00 as per metadata
            const hours = now.getHours().toString().padStart(2, '0');
            const minutes = now.getMinutes().toString().padStart(2, '0');
            time = `${hours}:${minutes}`;
        }

        const apiUrl = `https://api.nexray.web.id/maker/v1/iqc?text=${encodeURIComponent(qText)}&provider=${encodeURIComponent(provider)}&jam=${encodeURIComponent(time)}&baterai=${encodeURIComponent(battery)}`;

        await sock.sendMessage(m.chat, {
            image: { url: apiUrl },
            caption: `🎬 *IQC COMPLETED*\n\n• *Text:* ${qText}\n• *Provider:* ${provider}\n• *Time:* ${time}\n• *Battery:* ${battery}%\n\n_Generated by Liora Bot_`
        }, { quoted: m.quoted ? m.quoted.vM : m });
    } catch (e) {
        global.logger.error({ error: e.message, stack: e.stack }, "IQC Maker Error");
        m.reply(`❌ An error occurred while generating the quote image.`);
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["iqc"];
handler.tags = ["maker"];
handler.command = /^(iqc)$/i;

export default handler;
