/**
 * @file HD Video Enhancer plugin
 * @module plugins/maker/vhd
 * @description Enhance video resolution to 2K using unblurimage.ai API
 * @license Apache-2.0
 * @author ayakashigh11
 */

import crypto from "node:crypto";

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36';

/**
 * Generate headers for the API request
 * @param {string} serial - Product serial
 * @returns {object} - Headers
 */
function getHeaders(serial) {
    return {
        'accept': '*/*',
        'product-serial': serial,
        'user-agent': UA,
        'Referer': 'https://unblurimage.ai/'
    };
}

let handler = async (m, { sock, usedPrefix, command }) => {
    const q = m.quoted ? m.quoted : m;
    const mime = (q.msg || q).mimetype || q.mediaType || "";

    if (!/video/.test(mime)) {
        return m.reply(`🎬 *HD VIDEO ENHANCER*\n\nUsage: Reply to a video with *${usedPrefix + command}* to enhance quality to 2K.`);
    }

    try {
        await global.loading(m, sock);

        const videoBuffer = await q.download?.();
        if (!videoBuffer) return m.reply("❌ Failed to download the video. Please try again.");

        await m.reply("⏳ *Processing HD Video...* This process usually takes 1-3 minutes depending on length.");

        const serial = crypto.createHash('md5').update(UA + Date.now()).digest('hex');
        const fileName = crypto.randomBytes(3).toString('hex') + '_video.mp4';

        // Step 1: Request Upload URL
        const formReg = new FormData();
        formReg.append('video_file_name', fileName);

        const regRes = await fetch('https://api.unblurimage.ai/api/upscaler/v1/ai-video-enhancer/upload-video', {
            method: 'POST',
            headers: getHeaders(serial),
            body: formReg
        });

        const regData = await regRes.json();
        if (!regData.result?.url) throw new Error("Failed to get upload authorization.");

        const { url: ossUrl, object_name: objectName } = regData.result;

        // Step 2: Upload to OSS
        await fetch(ossUrl, {
            method: 'PUT',
            headers: {
                'Content-Type': 'video/mp4',
                'User-Agent': UA
            },
            body: videoBuffer
        });

        // Step 3: Create Processing Job
        const formJob = new FormData();
        formJob.append('original_video_file', `https://cdn.unblurimage.ai/${objectName}`);
        formJob.append('resolution', '2k');
        formJob.append('is_preview', 'false');

        const createRes = await fetch('https://api.unblurimage.ai/api/upscaler/v2/ai-video-enhancer/create-job', {
            method: 'POST',
            headers: getHeaders(serial),
            body: formJob
        });

        const createData = await createRes.json();
        const jobId = createData.result?.job_id;
        if (!jobId) throw new Error('Failed to create enhancement task.');

        // Step 4: Polling for Result
        let outputUrl = null;
        for (let i = 0; i < 60; i++) { // Max 5 minutes (60 * 5s)
            await new Promise(resolve => setTimeout(resolve, 5000));

            const checkRes = await fetch(`https://api.unblurimage.ai/api/upscaler/v2/ai-video-enhancer/get-job/${jobId}`, {
                headers: getHeaders(serial)
            });

            const checkData = await checkRes.json();
            if (checkData.result?.output_url) {
                outputUrl = checkData.result.output_url;
                break;
            }

            if (checkData.result?.status === 'failed') {
                throw new Error('API reported processing failure.');
            }
        }

        if (!outputUrl) throw new Error('Processing timeout. The video might be too long.');

        const caption = `🎬 *HD VIDEO SUCCESS*\n\n> Resolution: 2K Enhanced\n\n_Generated by Liora Bot_`;

        await sock.sendMessage(m.chat, {
            video: { url: outputUrl },
            caption: caption
        }, { quoted: m });

    } catch (e) {
        global.logger.error({ error: e.message, stack: e.stack }, "HD Video Plugin Error");
        m.reply(`❌ Error: ${e.message || "Failed to process video."}`);
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["hdvid", "hdvideo", "reminivid"];
handler.tags = ["maker"];
handler.command = /^(hdvid|hdvideo|unblurvideo|reminivid)$/i;

export default handler;
