/**
 * @file ID retrieval command handler
 * @module plugins/info/id
 * @license Apache-2.0
 * @author ayakashigh11
 */

let handler = async (m, { sock, args, usedPrefix, command }) => {
    const isChannel = command === "idch";
    const link = args[0];

    try {
        if (global.loading) await global.loading(m, sock);

        if (isChannel) {
            let id, meta;
            if (link && link.includes("whatsapp.com/channel/")) {
                const code = link.split("/channel/")[1].split("?")[0];
                meta = await sock.newsletterMetadata("invite", code, "GUEST");
                id = meta.id;
            } else if (m.chat.endsWith("@newsletter")) {
                id = m.chat;
                meta = await sock.newsletterMetadata("jid", id);
            } else {
                return m.reply(`Usage: ${usedPrefix + command} <channel_link>\nOr use it inside a channel.`);
            }

            const trd = meta.thread_metadata || {};
            const name = trd.name?.text || "Unknown";
            const subscribers = trd.subscribers_count || "0";
            const state = meta.state?.type || "Unknown";
            const verified = trd.verification === "VERIFIED" ? "Verified ✅" : "Not Verified ❌";

            const caption =
                `*CHANNEL INFO*\n\n` +
                `│ • *Name:* ${name}\n` +
                `│ • *ID:* ${id}\n` +
                `│ • *Followers:* ${subscribers}\n` +
                `│ • *Status:* ${state}\n` +
                `│ • *Verified:* ${verified}\n\n` +
                `_Generated by Liora Bot_`;

            const btns = [
                {
                    name: "cta_copy",
                    buttonParamsJson: JSON.stringify({
                        display_text: "Copy Channel ID",
                        copy_code: id,
                    }),
                },
            ];

            return await sock.client(m.chat, {
                text: caption,
                title: "Channel Information",
                footer: "Liora ID Tools",
                interactiveButtons: btns
            }, { quoted: m });
        } else {
            // Group ID
            let id, subject;
            if (link && link.includes("chat.whatsapp.com/")) {
                const code = link.split(".com/")[1].split("?")[0];
                const res = await sock.groupGetInviteInfo(code);
                id = res.id;
                subject = res.subject;
            } else if (m.isGroup) {
                id = m.chat;
                const metadata = await sock.groupMetadata(id);
                subject = metadata.subject;
                const members = metadata.participants?.length || 0;

                const caption =
                    `*GROUP INFO*\n\n` +
                    `│ • *Subject:* ${subject}\n` +
                    `│ • *ID:* ${id}\n` +
                    `│ • *Members:* ${members}\n\n` +
                    `_Generated by Liora Bot_`;

                const btns = [
                    {
                        name: "cta_copy",
                        buttonParamsJson: JSON.stringify({
                            display_text: "Copy Group ID",
                            copy_code: id,
                        }),
                    },
                ];

                return await sock.client(m.chat, {
                    text: caption,
                    title: "Group Information",
                    footer: "Liora ID Tools",
                    interactiveButtons: btns
                }, { quoted: m });
            } else {
                return m.reply(`Usage: ${usedPrefix + command} <group_link>\nOr use it inside a group.`);
            }
        }
    } catch (e) {
        m.reply(`Error: ${e.message}`);
    } finally {
        if (global.loading) await global.loading(m, sock, true);
    }
};

handler.help = ["idch", "idgc"];
handler.tags = ["info"];
handler.command = /^(idch|idgc)$/i;

export default handler;
