/**
 * @file Threads Downloader plugin
 * @module plugins/downloader/threads
 * @description Download media from Threads using NexRay API
 * @license Apache-2.0
 */

import fetch from "node-fetch";

let handler = async (m, { sock, text, usedPrefix, command }) => {
    if (!text) return m.reply(`Please provide a Threads post URL.\n\nUsage: *${usedPrefix + command} (url)*\nExample: *${usedPrefix + command} https://www.threads.com/@user/post/xxxxxx*`);

    const url = text.trim();
    if (!/threads\.net|threads\.com/i.test(url)) {
        return m.reply("❌ Invalid URL. Make sure it is a Threads link.");
    }

    try {
        await global.loading(m, sock);

        m.reply(`⏳ *Processing...* Fetching media from Threads.`);

        const res = await fetch(`https://api.nexray.web.id/downloader/threads?url=${encodeURIComponent(url)}`);

        if (!res.ok) throw new Error(`NexRay API error: ${res.statusText}`);

        const json = await res.json();
        if (!json.status || !json.result) {
            return m.reply(`❌ Failed to fetch media. Ensure the link is correct or try again later.`);
        }

        const { title, author, media } = json.result;

        if (!media || media.length === 0) {
            return m.reply("❌ No media found in this Threads post.");
        }

        const caption = `🧵 *THREADS DOWNLOADER*\n\n` +
            `• *Author:* ${author.full_name} (@${author.username})\n` +
            `• *Likes:* ${json.result.likes}\n` +
            `• *Content:* ${title || "-"}\n\n` +
            `_Generated by Liora Bot_`;

        for (const item of media) {
            const isVideo = item.url.includes(".mp4") || item.url.includes("video");

            if (isVideo) {
                await sock.sendMessage(m.chat, {
                    video: { url: item.url },
                    caption: caption
                }, { quoted: m });
            } else {
                await sock.sendMessage(m.chat, {
                    image: { url: item.url },
                    caption: caption
                }, { quoted: m });
            }
        }

    } catch (e) {
        global.logger.error({ error: e.message, url }, "Threads Downloader error");
        m.reply(`❌ An error occurred: ${e.message}`);
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["threads"];
handler.tags = ["downloader"];
handler.command = /^(threads)$/i;

export default handler;
