/**
 * @file YouTube Downloader plugin
 * @module plugins/downloader/youtube
 * @description Download YouTube videos (MP4) and audio (MP3) using NexRay API
 * @license Apache-2.0
 */

import fetch from "node-fetch";
import yts from "yt-search";

let handler = async (m, { sock, text, usedPrefix, command }) => {
    let args = text.trim().split(/\s+/);
    let input = args[0];
    let resSelected = args[1] || "1080"; // Default resolution 1080

    if (!input) {
        if (m.quoted?.text) {
            input = m.quoted.text.trim();
        } else {
            return m.reply(`Please provide a YouTube URL or search query.\n\nUsage: *${usedPrefix + command} (url/query) [resolution]*\nExample: *${usedPrefix + command} https://youtube.com/watch?v=xxx 720*`);
        }
    }

    try {
        await global.loading(m, sock);

        let url = input;
        // Search if not a URL
        if (!/^https?:\/\/(www\.)?(youtube\.com|youtu\.be)\//i.test(input)) {
            m.reply(`🔍 *Searching:* "${input}"...`);
            const search = await yts(input);
            if (!search.all || search.all.length === 0) {
                return m.reply("❌ No results found for your query.");
            }
            url = search.all[0].url;
        }

        m.reply(`⏳ *Processing...* Fetching download link from API.`);

        const isMp4 = command === "ytmp4";
        const apiUrl = isMp4
            ? `https://api.nexray.web.id/downloader/v1/ytmp4?url=${encodeURIComponent(url)}&resolusi=${resSelected}`
            : `https://api.nexray.web.id/downloader/v1/ytmp3?url=${encodeURIComponent(url)}`;

        const res = await fetch(apiUrl);
        if (!res.ok) throw new Error(`API error: ${res.statusText}`);

        const json = await res.json();
        if (!json.status || !json.result) {
            return m.reply(`❌ Failed to fetch download link. The video might be private, age-restricted, or the API is down.`);
        }

        const { title, author, duration, quality, url: downloadUrl } = json.result;

        if (!downloadUrl) {
            return m.reply("❌ No download link found in the API response.");
        }

        const formatTime = (seconds) => {
            const h = Math.floor(seconds / 3600);
            const m = Math.floor((seconds % 3600) / 60);
            const s = seconds % 60;
            return [h, m, s].map(v => v < 10 ? "0" + v : v).filter((v, i) => v !== "00" || i > 0).join(":");
        };

        const caption = `🎥 *YOUTUBE DOWNLOADER*\n\n` +
            `• *Title:* ${title}\n` +
            `• *Author:* ${author}\n` +
            `• *Duration:* ${formatTime(duration)}\n` +
            `• *Quality:* ${quality}\n\n` +
            `_Generated by Liora Bot_`;

        if (isMp4) {
            await sock.sendMessage(m.chat, {
                video: { url: downloadUrl },
                caption: caption,
                fileName: `${title}.mp4`,
                mimetype: "video/mp4"
            }, { quoted: m });
        } else {
            await sock.sendMessage(m.chat, {
                audio: { url: downloadUrl },
                mimetype: "audio/mpeg",
                fileName: `${title}.mp3`
            }, { quoted: m });
        }

    } catch (e) {
        global.logger.error({ error: e.message, input }, "YouTube Downloader API error");
        m.reply(`❌ An error occurred: ${e.message}`);
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["ytmp3", "ytmp4"];
handler.tags = ["downloader"];
handler.command = /^(ytmp3|ytmp4)$/i;

export default handler;
