/**
 * @file Google Drive Downloader plugin
 * @module plugins/downloader/gdrive
 * @description Download files or view folder contents from Google Drive
 * @license Apache-2.0
 * @author ayakashigh11
 */

const API_KEY = "AIzaSyAA9ERw-9LZVEohRYtCWka_TQc6oXmvcVU";

/**
 * Extracts the file ID from a Google Drive URL
 * @param {string} url - The Drive URL
 * @returns {string|null} - The extracted file ID
 */
function extractFileId(url) {
    const patterns = [
        /\/file\/d\/([a-zA-Z0-9_-]+)/,
        /\/folders\/([a-zA-Z0-9_-]+)/,
        /id=([a-zA-Z0-9_-]+)/,
        /^([a-zA-Z0-9_-]+)$/
    ];
    for (const p of patterns) {
        const m = url.match(p);
        if (m) return m[1];
    }
    return null;
}

/**
 * Formats file size into a readable string
 * @param {string|number} size - Size in bytes
 * @returns {string} - Formatted size
 */
function formatSize(size) {
    const bytes = parseInt(size);
    if (isNaN(bytes)) return "N/A";
    if (bytes >= 1024 * 1024 * 1024) return (bytes / (1024 * 1024 * 1024)).toFixed(2) + " GB";
    if (bytes >= 1024 * 1024) return (bytes / (1024 * 1024)).toFixed(2) + " MB";
    if (bytes >= 1024) return (bytes / 1024).toFixed(2) + " KB";
    return bytes + " B";
}

let handler = async (m, { sock, text, usedPrefix, command }) => {
    const input = text || m.quoted?.text;
    if (!input) {
        return m.reply(`🎬 *GOOGLE DRIVE DOWNLOADER*\n\nUsage: *${usedPrefix + command} [drive-url]*\nExample: *${usedPrefix + command} https://drive.google.com/file/d/xxxx/view*`);
    }

    const fileId = extractFileId(input);
    if (!fileId) {
        return m.reply("❌ Invalid Google Drive URL. Please provide a valid link.");
    }

    try {
        await global.loading(m, sock);

        // Fetch Metadata
        const metaUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?key=${API_KEY}&fields=id,name,mimeType,size,createdTime`;
        const metaRes = await fetch(metaUrl);

        if (!metaRes.ok) {
            const err = await metaRes.json();
            throw new Error(err.error?.message || `API returned ${metaRes.status}`);
        }

        const metadata = await metaRes.json();

        // Handle Folder
        if (metadata.mimeType === "application/vnd.google-apps.folder") {
            const listUrl = `https://www.googleapis.com/drive/v3/files?key=${API_KEY}&q='${fileId}'+in+parents&fields=files(id,name,mimeType,size,createdTime)`;
            const listRes = await fetch(listUrl);
            const listData = await listRes.json();
            const files = listData.files || [];

            let caption = `📁 *GOOGLE DRIVE FOLDER*\n\n` +
                `• *Name:* ${metadata.name}\n` +
                `• *Total Files:* ${files.length}\n` +
                `• *Created:* ${new Date(metadata.createdTime).toLocaleString()}\n\n` +
                `*Contents (top 10):*\n`;

            files.slice(0, 10).forEach((f, i) => {
                caption += `${i + 1}. ${f.name} (${formatSize(f.size)})\n`;
            });

            if (files.length > 10) {
                caption += `\n_...and ${files.length - 10} more files_`;
            }

            caption += `\n\n_Generated by Liora Bot_`;
            return m.reply(caption);
        }

        // Handle File
        const caption = `📄 *GOOGLE DRIVE FILE*\n\n` +
            `• *Name:* ${metadata.name}\n` +
            `• *Size:* ${formatSize(metadata.size)}\n` +
            `• *Type:* ${metadata.mimeType}\n` +
            `• *Created:* ${new Date(metadata.createdTime).toLocaleString()}\n\n` +
            `_Generated by Liora Bot_`;

        await m.reply(`⏳ *Processing...* Fetching file data.`);

        const downloadUrl = `https://www.googleapis.com/drive/v3/files/${fileId}?alt=media&key=${API_KEY}`;

        await sock.sendMessage(m.chat, {
            document: { url: downloadUrl },
            fileName: metadata.name,
            mimetype: metadata.mimeType,
            caption: caption
        }, { quoted: m });

    } catch (e) {
        global.logger.error({ error: e.message, stack: e.stack }, "GDrive Downloader Error");
        m.reply(`❌ Error: ${e.message}`);
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["gdrive"];
handler.tags = ["downloader"];
handler.command = /^(googledrivedl|gdrive|gdv)$/i;

export default handler;
