/**
 * @file TikTok Downloader plugin
 * @module plugins/downloader/tiktok
 * @description Download TikTok videos using Danzy API
 * @license Apache-2.0
 */

import fetch from "node-fetch";

let handler = async (m, { text, usedPrefix, command }) => {
    if (!text) return m.reply(`Enter the TikTok URL you want to download.\n\nExample: *${usedPrefix + command} https://vm.tiktok.com/xxxxxx/*`);

    const tiktokUrl = text.trim();
    if (!/tiktok\.com/i.test(tiktokUrl)) {
        return m.reply("❌ Invalid URL. Make sure it is a TikTok link.");
    }

    try {
        await m.reply(`⏳ *Processing...* Downloading TikTok video.`);

        const res = await fetch(`https://api.danzy.web.id/api/download/tiktok?url=${encodeURIComponent(tiktokUrl)}`);

        if (!res.ok) throw new Error(`Danzy API error: ${res.statusText}`);

        const json = await res.json();
        if (!json.status || !json.data) {
            return m.reply(`❌ Failed to download video. Ensure the link is correct or try again later.`);
        }

        const { title, author, links } = json.data;
        const videoUrl = links[0]; // Primary download link

        if (!videoUrl || videoUrl === "/") {
            return m.reply("❌ No download link found for this video.");
        }

        const caption = `🎬 *TIKTOK DOWNLOADER*\n\n` +
            `• *Title:* ${title || "No Title"}\n` +
            `• *Author:* ${author || "Unknown"}\n\n` +
            `_Generated by Liora Bot_`;

        await this.sendMessage(m.chat, {
            video: { url: videoUrl },
            caption: caption,
            fileName: `tiktok_${Date.now()}.mp4`,
            mimetype: "video/mp4"
        }, { quoted: m });

    } catch (e) {
        console.error("TikTok Downloader Error:", e);
        m.reply(`❌ An error occurred while processing your request.`);
    }
};

handler.help = ["tt", "tiktok", "tiktokdownload"];
handler.tags = ["downloader"];
handler.command = /^(tt|tiktok|tiktokdownload)$/i;

export default handler;
