/**
 * @file TikTok Downloader & Search plugin
 * @module plugins/downloader/tiktok
 * @description Download TikTok videos/images or search videos using TikWM API
 * @license Apache-2.0
 * @author ayakashigh11
 */

function formatNumber(number) {
    return number ? number.toLocaleString() : "0";
}

function formatDuration(seconds) {
    if (!seconds) return "00:00";
    const m = Math.floor(seconds / 60).toString().padStart(2, "0");
    const s = Math.floor(seconds % 60).toString().padStart(2, "0");
    return `${m}:${s}`;
}

let handler = async (m, { sock, text, usedPrefix, command }) => {
    try {
        const input = text.trim();
        const regex = /(https:\/\/(vt|vm)\.tiktok\.com\/[^\s]+|https:\/\/www\.tiktok\.com\/@[\w.-]+\/video\/\d+)/;
        const parseUrl = input.match(regex)?.[0];

        if (parseUrl) {
            await global.loading(m, sock);
            const res = await fetch(`https://www.tikwm.com/api/?url=${encodeURIComponent(parseUrl)}&hd=1`).then(r => r.json());

            if (!res || !res.data) return m.reply("❌ Failed to fetch data from TikTok.");

            const data = res.data;
            const caption = `🎬 *TIKTOK DOWNLOADER*\n\n` +
                `• *Title:* ${data.title || "No Title"}\n` +
                `• *Region:* ${data.region || "Unknown"}\n` +
                `• *Duration:* ${formatDuration(data.duration)}\n` +
                `• *Views:* ${formatNumber(data.play_count)}\n` +
                `• *Comments:* ${formatNumber(data.comment_count)}\n` +
                `• *Shares:* ${formatNumber(data.share_count)}\n` +
                `• *Author:* ${data.author?.nickname || data.author?.unique_id || "Unknown"}\n\n` +
                `_Generated by Liora Bot_`;

            await m.reply(`⏳ *Processing...* Sending media.`);

            // Handle Slide/Images
            if (data.images && data.images.length > 0) {
                if (data.images.length === 1) {
                    await sock.sendMessage(m.chat, { image: { url: data.images[0] }, caption }, { quoted: m });
                } else {
                    const albumData = {
                        album: data.images.map(img => ({ image: { url: img } }))
                    };
                    await m.reply(caption);
                    // Liora's advanced album sender from mod.js
                    await sock.client(m.chat, albumData, { quoted: m });
                }
            } else if (data.play) {
                // Handle Video
                await sock.sendMessage(m.chat, {
                    video: { url: data.play },
                    caption: caption
                }, { quoted: m });
            }

            // Handle Audio
            if (data.music_info?.play) {
                await sock.sendMessage(m.chat, {
                    audio: { url: data.music_info.play },
                    mimetype: "audio/mpeg",
                    ptt: false
                }, { quoted: m });
            }

        } else if (input) {
            // Handle Search
            await global.loading(m, sock);
            const search = await fetch(`https://www.tikwm.com/api/feed/search?keywords=${encodeURIComponent(input)}&count=1&cursor=0&web=1&hd=1`).then(r => r.json());
            const video = search?.data?.videos?.[0];

            if (!video) return m.reply(`❌ No video found for search: "${input}".`);

            const caption = `🎬 *TIKTOK PLAYER*\n\n` +
                `• *Title:* ${video.title || "No Title"}\n` +
                `• *Region:* ${video.region || "Unknown"}\n` +
                `• *Duration:* ${formatDuration(video.duration)}\n` +
                `• *Views:* ${formatNumber(video.play_count)}\n` +
                `• *Comments:* ${formatNumber(video.comment_count)}\n` +
                `• *Shares:* ${formatNumber(video.share_count)}\n` +
                `• *Author:* ${video.author?.nickname || video.author?.unique_id || "Unknown"}\n\n` +
                `_Generated by Liora Bot_`;

            const playUrl = video.play.startsWith("http") ? video.play : `https://www.tikwm.com${video.play}`;

            await sock.sendMessage(m.chat, {
                video: { url: playUrl },
                caption
            }, { quoted: m });

        } else {
            // Help Message
            const helpMsg = `🎬 *TIKTOK DOWNLOADER & SEARCH*\n\n` +
                `• *Search:* \`${usedPrefix + command} [query]\`\n` +
                `• *Download:* \`${usedPrefix + command} [link]\`\n\n` +
                `*Example:*\n` +
                `• ${usedPrefix + command} funny cats\n` +
                `• ${usedPrefix + command} https://vt.tiktok.com/xxxxx`;

            m.reply(helpMsg);
        }
    } catch (err) {
        global.logger.error({ error: err.message, stack: err.stack }, "TikTok Plugin Error");
        m.reply("⚠️ An error occurred while processing your request.");
    } finally {
        await global.loading(m, sock, true);
    }
};

handler.help = ["tiktok"];
handler.tags = ["downloader"];
handler.command = /^(tt|tiktok)$/i;

export default handler;
